version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inhouse_qase_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/inhouse_qase?schema=public
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-super-secret-dev-key}
    depends_on:
      - db
    volumes:
      - reports_data:/app/public/reports
    networks:
      - qase_network

  db:
    image: postgres:15-alpine
    container_name: inhouse_qase_db_prod
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inhouse_qase
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    networks:
      - qase_network

volumes:
  pgdata_prod:
  reports_data:

networks:
  qase_network:
