import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";
import { getSessionUser, unauthorized } from "@/lib/api-auth";

// Static monitor dashboards live in public/monitor/<slug>/index.html and are
// regenerated by a script outside this app (it holds the Jira/Qase tokens, this
// process deliberately does not). The refresh button therefore only leaves a
// request marker; a cron job on the host picks it up within a minute and does
// the work. Worst case for this route being reachable is one extra refresh.
const STATE_DIR = process.env.MONITOR_STATE_DIR || "/home/ubuntu/tms-monitor/state";
const SLUGS = new Set(["stsd"]);
const MIN_INTERVAL_MS = 60_000;

function paths(slug: string) {
  return {
    request: path.join(STATE_DIR, `${slug}.request`),
    log: path.join(STATE_DIR, `${slug}.last`),
    page: path.join(process.cwd(), "public", "monitor", slug, "index.html"),
  };
}

async function mtime(file: string) {
  try {
    return (await fs.stat(file)).mtime.toISOString();
  } catch {
    return null;
  }
}

/** Freshness of the generated page, so the button can tell when a refresh landed. */
export async function GET(_req: Request, ctx: { params: Promise<{ slug: string }> }) {
  const { slug } = await ctx.params;
  if (!SLUGS.has(slug)) return NextResponse.json({ error: "Unknown dashboard" }, { status: 404 });
  if (!(await getSessionUser())) return unauthorized();

  const p = paths(slug);
  const [generatedAt, requestedAt, lastRun] = await Promise.all([
    mtime(p.page),
    mtime(p.request),
    fs.readFile(p.log, "utf8").then((t) => t.trim()).catch(() => null),
  ]);
  return NextResponse.json(
    { slug, generatedAt, pending: requestedAt !== null, requestedAt, lastRun },
    { headers: { "cache-control": "no-store" } },
  );
}

/** Ask the host to regenerate the page. */
export async function POST(_req: Request, ctx: { params: Promise<{ slug: string }> }) {
  const { slug } = await ctx.params;
  if (!SLUGS.has(slug)) return NextResponse.json({ error: "Unknown dashboard" }, { status: 404 });

  const user = await getSessionUser();
  if (!user) return unauthorized();

  const p = paths(slug);
  const requestedAt = await mtime(p.request);
  if (requestedAt && Date.now() - Date.parse(requestedAt) < MIN_INTERVAL_MS) {
    // A refresh is already queued; say so rather than piling up requests.
    return NextResponse.json({ slug, queued: false, pending: true, requestedAt }, { status: 202 });
  }

  try {
    await fs.mkdir(STATE_DIR, { recursive: true });
    await fs.writeFile(p.request, `${new Date().toISOString()} ${user.id}\n`, "utf8");
  } catch (error: any) {
    return NextResponse.json(
      { error: "Cannot queue a refresh on this host", detail: String(error?.code || error) },
      { status: 503 },
    );
  }
  return NextResponse.json({ slug, queued: true, pending: true }, { status: 202 });
}
