import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(
  req: Request,
  { params }: { params: Promise<{ code: string, caseId: string }> }
) {
  const { code, caseId } = await params;
  
  try {
    const testCase = await prisma.testCase.findUnique({
      where: { id: caseId },
      include: { 
        suite: true,
        project: true
      }
    });

    if (!testCase || !testCase.automationScript) {
      return NextResponse.json({ error: "Test case or script not found" }, { status: 404 });
    }

    const GITHUB_TOKEN = testCase.project.githubToken || process.env.GITHUB_TOKEN;
    const GITHUB_OWNER = testCase.project.githubOwner || process.env.GITHUB_OWNER;
    const GITHUB_REPO = testCase.project.githubRepo || process.env.GITHUB_REPO;

    if (!GITHUB_TOKEN || !GITHUB_OWNER || !GITHUB_REPO) {
      return NextResponse.json({ 
        error: "GitHub integration is not configured. Please set it in Project Settings -> Integrations." 
      }, { status: 400 });
    }

    const headers = {
      "Authorization": `Bearer ${GITHUB_TOKEN}`,
      "Accept": "application/vnd.github.v3+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json"
    };

    const baseUrl = `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}`;

    // 1. Get main branch SHA
    const refRes = await fetch(`${baseUrl}/git/refs/heads/main`, { headers });
    if (!refRes.ok) {
      const err = await refRes.json();
      throw new Error(`Failed to get main branch: ${err.message}`);
    }
    const refData = await refRes.json();
    const mainSha = refData.object.sha;

    // 2. Create new branch
    const branchName = `automation/test-${caseId}-${Date.now()}`;
    const createBranchRes = await fetch(`${baseUrl}/git/refs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: mainSha
      })
    });
    
    if (!createBranchRes.ok) {
      const err = await createBranchRes.json();
      throw new Error(`Failed to create branch: ${err.message}`);
    }

    // 3. Prepare the file content
    const suiteName = testCase.suite?.title.replace(/[^a-zA-Z0-9]/g, '-') || 'ungrouped';
    const slugTitle = testCase.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const shortId = caseId.substring(0, 4);
    const filePath = `tests/${suiteName}/${code}-${shortId}-${slugTitle}.spec.ts`;
    
    const isWrapped = testCase.automationScript.includes("test(");
    const finalScript = isWrapped 
      ? testCase.automationScript 
      : `import { test, expect } from '@playwright/test';\n\ntest('${testCase.title.replace(/'/g, "\\'")}', async ({ page }) => {\n${testCase.automationScript}\n});`;

    const contentEncoded = Buffer.from(finalScript).toString("base64");

    // 4. Create the file in the new branch
    const createFileRes = await fetch(`${baseUrl}/contents/${filePath}`, {
      method: 'PUT',
      headers,
      body: JSON.stringify({
        message: `Add automated test for: ${testCase.title}`,
        content: contentEncoded,
        branch: branchName
      })
    });

    if (!createFileRes.ok) {
      const err = await createFileRes.json();
      throw new Error(`Failed to create file: ${err.message}`);
    }

    // 5. Create Pull Request
    const createPrRes = await fetch(`${baseUrl}/pulls`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        title: `[Auto] Automated Test: ${testCase.title}`,
        body: `This PR adds an automated Playwright test generated by Qase Clone for test case **${testCase.title}**.\n\nCase ID: \`${caseId}\``,
        head: branchName,
        base: 'main'
      })
    });

    if (!createPrRes.ok) {
      const err = await createPrRes.json();
      throw new Error(`Failed to create Pull Request: ${err.message}`);
    }

    const prData = await createPrRes.json();
    const prUrl = prData.html_url;

    // 6. Update Database
    await prisma.testCase.update({
      where: { id: caseId },
      data: { githubPrUrl: prUrl }
    });

    return NextResponse.json({ success: true, prUrl });

  } catch (error: any) {
    console.error("GitHub PR error:", error);
    return NextResponse.json({ error: error.message || "An unexpected error occurred" }, { status: 500 });
  }
}
